import type { ResearchIndexRepository, ResearchSearchQuery, ResearchTopicQuery, ResearchDocumentQuery, ResearchIndexApplySummary, ResearchSearchHit, ResearchDocumentIndex, ResearchTopicIndex } from '@luoome/core';
import { and, asc, desc, eq, gte, like, lte, or, sql } from 'drizzle-orm';
import { researchDocumentChunks, researchDocumentIndex, researchSubjectLinks, researchTopicDocuments, researchTopicIndex, type Schema } from '../../schema/index.js';
import type { DrizzleDb } from '../../client.js';

const topicFrom = (r: typeof researchTopicIndex.$inferSelect): ResearchTopicIndex => ({ ...r, tags: r.tags ?? [], archivedAt: r.archivedAt ?? undefined, summary: r.summary ?? undefined, diagnostic: r.diagnostic ?? undefined, availability: r.availability as ResearchTopicIndex['availability'] });
const documentFrom = (r: typeof researchDocumentIndex.$inferSelect): ResearchDocumentIndex => ({ ...r, tags: r.tags ?? [], attachmentPaths: r.attachmentPaths ?? [], author: r.author ?? undefined, sourceUrl: r.sourceUrl ?? undefined, sourceStatus: r.sourceStatus as ResearchDocumentIndex['sourceStatus'], publishedAt: r.publishedAt ?? undefined, observedAt: r.observedAt ?? undefined, excerpt: r.excerpt ?? undefined, diagnostic: r.diagnostic ?? undefined, kind: r.kind as ResearchDocumentIndex['kind'], availability: r.availability as ResearchDocumentIndex['availability'] });
const topicRow = (x: ResearchTopicIndex): typeof researchTopicIndex.$inferInsert => ({ ...x, archivedAt: x.archivedAt ?? null, summary: x.summary ?? null, diagnostic: x.diagnostic ?? null });
const documentRow = (x: ResearchDocumentIndex): typeof researchDocumentIndex.$inferInsert => ({ ...x, author: x.author ?? null, sourceUrl: x.sourceUrl ?? null, sourceStatus: x.sourceStatus ?? null, publishedAt: x.publishedAt ?? null, observedAt: x.observedAt ?? null, excerpt: x.excerpt ?? null, diagnostic: x.diagnostic ?? null });
export class DrizzleResearchIndexRepository implements ResearchIndexRepository {
  constructor(private readonly db: DrizzleDb) {}
  async applyIndexBatch(input: Parameters<ResearchIndexRepository['applyIndexBatch']>[0]): Promise<ResearchIndexApplySummary> {
    let added = 0, updated = 0, unchanged = 0, missing = 0;
    this.db.transaction((tx) => {
      for (const x of input.topics) { const old = tx.select({ hash: researchTopicIndex.contentHash, path: researchTopicIndex.relativePath }).from(researchTopicIndex).where(eq(researchTopicIndex.id, x.id)).get(); if (!old) added++; else if (old.hash === x.contentHash && old.path === x.relativePath) unchanged++; else updated++; tx.insert(researchTopicIndex).values(topicRow(x)).onConflictDoUpdate({ target: researchTopicIndex.id, set: topicRow(x) }).run(); }
      for (const x of input.documents) { const old = tx.select({ hash: researchDocumentIndex.contentHash, path: researchDocumentIndex.relativePath }).from(researchDocumentIndex).where(eq(researchDocumentIndex.id, x.id)).get(); if (!old) added++; else if (old.hash === x.contentHash && old.path === x.relativePath) unchanged++; else updated++; tx.insert(researchDocumentIndex).values(documentRow(x)).onConflictDoUpdate({ target: researchDocumentIndex.id, set: documentRow(x) }).run(); }
      if (input.completeness === 'complete') { for (const row of tx.select().from(researchTopicIndex).where(eq(researchTopicIndex.vaultId, input.vaultId)).all()) if (!input.seenTopicIds.has(row.id) && row.availability !== 'missing') { tx.update(researchTopicIndex).set({ availability: 'missing', diagnostic: '文件未在最近一次完整扫描中出现' }).where(eq(researchTopicIndex.id, row.id)).run(); missing++; } for (const row of tx.select().from(researchDocumentIndex).where(eq(researchDocumentIndex.vaultId, input.vaultId)).all()) if (!input.seenDocumentIds.has(row.id) && row.availability !== 'missing') { tx.update(researchDocumentIndex).set({ availability: 'missing', diagnostic: '文件未在最近一次完整扫描中出现' }).where(eq(researchDocumentIndex.id, row.id)).run(); missing++; } }
      for (const x of input.topics) { tx.delete(researchSubjectLinks).where(and(eq(researchSubjectLinks.ownerKind, 'topic'), eq(researchSubjectLinks.ownerId, x.id))).run(); }
      for (const x of input.documents) { tx.delete(researchSubjectLinks).where(and(eq(researchSubjectLinks.ownerKind, 'document'), eq(researchSubjectLinks.ownerId, x.id))).run(); tx.delete(researchTopicDocuments).where(eq(researchTopicDocuments.documentId, x.id)).run(); tx.delete(researchDocumentChunks).where(eq(researchDocumentChunks.documentId, x.id)).run(); }
      if (input.subjectLinks.length) tx.insert(researchSubjectLinks).values(input.subjectLinks).onConflictDoNothing().run();
      if (input.topicDocuments.length) tx.insert(researchTopicDocuments).values(input.topicDocuments.map((x) => ({ topicId: x.topicId, documentId: x.documentId, relation: x.relation, sortOrder: x.order ?? null }))).onConflictDoNothing().run();
      if (input.chunks.length) tx.insert(researchDocumentChunks).values(input.chunks.map((x) => ({ documentId: x.documentId, ordinal: x.ordinal, headingPath: x.headingPath, contentHash: x.contentHash, body: x.body }))).onConflictDoNothing().run();
    });
    return { added, updated, unchanged, missing, invalid: [...input.topics, ...input.documents].filter((x) => x.availability === 'invalid').length, conflicts: [...input.topics, ...input.documents].filter((x) => x.availability === 'conflict').length };
  }
  async findTopic(id: string) { const row = this.db.select().from(researchTopicIndex).where(eq(researchTopicIndex.id, id)).get(); return row ? topicFrom(row) : null; }
  async findDocument(id: string) { const row = this.db.select().from(researchDocumentIndex).where(eq(researchDocumentIndex.id, id)).get(); return row ? documentFrom(row) : null; }
  async listTopics(query: ResearchTopicQuery) { const rows = this.db.select().from(researchTopicIndex).where(and(query.kind ? eq(researchTopicIndex.kind, query.kind) : undefined, query.availability ? eq(researchTopicIndex.availability, query.availability) : undefined, query.includeArchived ? undefined : sql`${researchTopicIndex.archivedAt} IS NULL`)).orderBy(desc(researchTopicIndex.indexedAt), asc(researchTopicIndex.id)).all().map(topicFrom).filter((x) => !query.subject || this.db.select().from(researchSubjectLinks).where(and(eq(researchSubjectLinks.ownerKind, 'topic'), eq(researchSubjectLinks.ownerId, x.id), eq(sql`(${researchSubjectLinks.subjectKind} || ':' || ${researchSubjectLinks.subjectKey})`, query.subject))).get() !== undefined).filter((x) => !query.tags?.length || query.tags.every((tag) => x.tags.includes(tag))); return rows.slice(0, query.limit ?? 50); }
  async listDocuments(query: ResearchDocumentQuery) { const rows = this.db.select().from(researchDocumentIndex).where(and(query.kind ? eq(researchDocumentIndex.kind, query.kind) : undefined, query.availability ? eq(researchDocumentIndex.availability, query.availability) : undefined, query.publishedFrom ? gte(researchDocumentIndex.publishedAt, query.publishedFrom) : undefined, query.publishedTo ? lte(researchDocumentIndex.publishedAt, query.publishedTo) : undefined)).orderBy(desc(researchDocumentIndex.observedAt), desc(researchDocumentIndex.publishedAt), desc(researchDocumentIndex.importedAt), asc(researchDocumentIndex.id)).all().map(documentFrom).filter((x) => !query.topicId || this.db.select().from(researchTopicDocuments).where(and(eq(researchTopicDocuments.topicId, query.topicId), eq(researchTopicDocuments.documentId, x.id))).get() !== undefined).filter((x) => !query.subject || this.db.select().from(researchSubjectLinks).where(and(eq(researchSubjectLinks.ownerKind, 'document'), eq(researchSubjectLinks.ownerId, x.id), eq(sql`(${researchSubjectLinks.subjectKind} || ':' || ${researchSubjectLinks.subjectKey})`, query.subject))).get() !== undefined).filter((x) => !query.tags?.length || query.tags.every((tag) => x.tags.includes(tag))); return rows.slice(0, query.limit ?? 50); }
  async searchDocuments(query: ResearchSearchQuery): Promise<readonly ResearchSearchHit[]> { const rows = this.db.select({ document: researchDocumentIndex, headingPath: researchDocumentChunks.headingPath, body: researchDocumentChunks.body }).from(researchDocumentChunks).innerJoin(researchDocumentIndex, eq(researchDocumentIndex.id, researchDocumentChunks.documentId)).where(or(like(researchDocumentChunks.body, `%${query.text}%`), like(researchDocumentIndex.title, `%${query.text}%`))).limit(query.limit ?? 50).all(); return rows.map((r) => ({ document: documentFrom(r.document), headingPath: r.headingPath, snippet: r.body.slice(0, 500), score: 1 })); }
}
