import { createHash } from 'node:crypto';
import { promises as fs } from 'node:fs';
import { dirname, extname, join, relative, resolve, sep } from 'node:path';
import { ResearchVaultAdapterLike, type ResearchVaultEntry } from '@luoome/core';

const hash = (data: Uint8Array | string) => createHash('sha256').update(data).digest('hex');
const isInside = (root: string, candidate: string) => candidate === root || candidate.startsWith(`${root}${sep}`);
const safeRelative = (value: string) => { const normalized = value.replaceAll('\\', '/'); if (!normalized || normalized.startsWith('/') || normalized.includes('\0') || normalized.split('/').includes('..')) throw new Error('unsafe relative path'); return normalized; };
const ignored = (name: string) => name.startsWith('.') || name === 'Thumbs.db' || name.endsWith('~');

export interface ObsidianVaultOptions { readonly vaultPath: string; readonly researchRoot?: string; readonly managedRoot?: string; readonly vaultId?: string; readonly maxTextBytes?: number; }
export class ObsidianVaultAdapter implements ResearchVaultAdapterLike {
  readonly name = 'obsidian-vault'; readonly vaultId: string; private readonly root: string; private readonly researchRoot: string; private readonly managedRoot: string; private readonly maxTextBytes: number;
  constructor(options: ObsidianVaultOptions) { if (!options.vaultPath.startsWith('/')) throw new Error('vault path must be absolute'); this.root = resolve(options.vaultPath); this.researchRoot = safeRelative(options.researchRoot ?? 'Research'); this.managedRoot = safeRelative(options.managedRoot ?? 'Research/Luoome'); if (!this.managedRoot.startsWith(`${this.researchRoot}/`) && this.managedRoot !== this.researchRoot) throw new Error('managed root must be inside research root'); this.vaultId = options.vaultId ?? hash(this.root).slice(0, 16); this.maxTextBytes = options.maxTextBytes ?? 10 * 1024 * 1024; }
  private async target(path: string) { const rel = safeRelative(path); const target = resolve(this.root, rel); if (!isInside(this.root, target)) throw new Error('path escapes vault'); const parent = await fs.realpath(dirname(target)).catch(() => dirname(target)); if (!isInside(this.root, parent)) throw new Error('path escapes vault'); return { rel, target }; }
  async scan(input?: { readonly roots?: readonly string[] }): Promise<readonly ResearchVaultEntry[]> { const roots = input?.roots?.length ? input.roots.map(safeRelative) : [this.researchRoot]; const output: ResearchVaultEntry[] = []; const walk = async (relRoot: string): Promise<void> => { const { target } = await this.target(relRoot); const dir = await fs.opendir(target); for await (const entry of dir) { if (ignored(entry.name)) continue; const rel = `${relRoot}/${entry.name}`; if (entry.isSymbolicLink()) { const real = await fs.realpath(join(this.root, rel)).catch(() => ''); if (!isInside(this.root, real)) continue; } if (entry.isDirectory()) await walk(rel); else if (entry.isFile() && extname(entry.name).toLowerCase() === '.md') { const st = await fs.stat(join(this.root, rel)); if (st.size > this.maxTextBytes) continue; const content = await fs.readFile(join(this.root, rel)); output.push({ relativePath: rel, size: st.size, modifiedAt: st.mtime, contentHash: hash(content) }); } } }; for (const root of roots) await walk(root); return output.sort((a, b) => a.relativePath.localeCompare(b.relativePath)); }
  async readText(input: { readonly relativePath: string; readonly maxBytes: number }) { const { target } = await this.target(input.relativePath); const st = await fs.stat(target); if (st.size > input.maxBytes) throw new Error('file exceeds configured size limit'); return fs.readFile(target, 'utf8'); }
  async createManagedDocument(input: { readonly relativePath: string; readonly content: string }) { const rel = safeRelative(input.relativePath); if (!rel.startsWith(`${this.managedRoot}/`)) throw new Error('managed writes must stay inside managed root'); const { target } = await this.target(rel); await fs.mkdir(dirname(target), { recursive: true }); try { await fs.stat(target); throw new Error('target already exists'); } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; } const tmp = `${target}.luoome-${process.pid}-${Date.now()}.tmp`; const handle = await fs.open(tmp, 'wx'); try { await handle.writeFile(input.content, 'utf8'); await handle.sync(); } finally { await handle.close(); } await fs.rename(tmp, target); const st = await fs.stat(target); return { relativePath: rel, size: st.size, modifiedAt: st.mtime, contentHash: hash(input.content) }; }
  async importAttachment(input: { readonly suggestedName: string; readonly content: Uint8Array; readonly mediaType: string }) { const ext = extname(input.suggestedName).replace(/[^a-zA-Z0-9.]/g, '').slice(0, 10); const rel = `${this.managedRoot}/Attachments/${hash(input.content)}${ext}`; const { target } = await this.target(rel); await fs.mkdir(dirname(target), { recursive: true }); try { await fs.stat(target); } catch { await fs.writeFile(target, input.content, { flag: 'wx' }); } const st = await fs.stat(target); return { relativePath: rel, size: st.size, modifiedAt: st.mtime, contentHash: hash(input.content) }; }
  buildOpenUri(relativePath: string) { const rel = safeRelative(relativePath); return `obsidian://open?vault=${encodeURIComponent(this.vaultId)}&file=${encodeURIComponent(rel.replaceAll('/', '/'))}`; }
}

export interface ParsedMarkdown { readonly frontmatter: Record<string, string | string[] | undefined>; readonly body: string; }
export const parseResearchMarkdown = (content: string): ParsedMarkdown => { if (!content.startsWith('---\n')) return { frontmatter: {}, body: content }; const end = content.indexOf('\n---', 4); if (end < 0) throw new Error('frontmatter terminator missing'); const frontmatter: Record<string, string | string[] | undefined> = {}; let current: string | undefined; for (const line of content.slice(4, end).split('\n')) { const list = line.match(/^\s+-\s+(.*)$/); if (list && current) { const previous = frontmatter[current]; frontmatter[current] = [...(Array.isArray(previous) ? previous : []), list[1].trim().replace(/^['"]|['"]$/g, '')]; continue; } const match = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/); if (!match) continue; current = match[1]; const raw = match[2].trim(); frontmatter[current] = raw === '' ? undefined : raw.replace(/^['"]|['"]$/g, ''); } return { frontmatter, body: content.slice(end + 4).replace(/^\n/, '') }; };
